name: Release build
on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - id: versions
        run: |
          make show-versions >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: ghcr.io/cosmo/code-server:${{ needs.versions.outputs.tag }}
          build-args: |
            CODE_SERVER_BASE_TAG=${{ needs.versions.outputs.code-server-basetag }}
            GOLANG_VERSION=${{ needs.versions.outputs.go-version }}
            NODE_VERSION=${{ needs.versions.outputs.node-version }}
            PYTHON_VERSION=${{ needs.versions.outputs.python-version }}
            DOCKER_VERSION=${{ needs.versions.outputs.docker-version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
