name: Release build
on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - id: versions
        run: |
          make print-TAG                  >> "$GITHUB_OUTPUT"
          make print-CODE_SERVER_BASE_TAG >> "$GITHUB_OUTPUT"
          make print-GOLANG_VERSION       >> "$GITHUB_OUTPUT"
          make print-NODE_VERSION         >> "$GITHUB_OUTPUT"
          make print-PYTHON_VERSION       >> "$GITHUB_OUTPUT"
          make print-DOCKER_VERSION       >> "$GITHUB_OUTPUT"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: ghcr.io/cosmo/code-server:${{ steps.versions.outputs.TAG }}
          build-args: |
            CODE_SERVER_BASE_TAG=${{ steps.versions.outputs.CODE_SERVER_BASE_TAG }}
            GOLANG_VERSION=${{ steps.versions.outputs.GOLANG_VERSION }}
            NODE_VERSION=${{ steps.versions.outputs.NODE_VERSION }}
            PYTHON_VERSION=${{ steps.versions.outputs.PYTHON_VERSION }}
            DOCKER_VERSION=${{ steps.versions.outputs.DOCKER_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
